"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]

prepend_keymap = [
  { on = [
    "w",
  ], exec = 'shell "$SHELL" --block --confirm', desc = "Open shell here" },
  { on = [
    "W",
  ], exec = "tasks_show" },

  # Navigation
  { on = [
    "i",
  ], exec = "arrow -1" },
  { on = [
    "e",
  ], exec = "arrow 1" },

  { on = [
    "E",
  ], exec = "arrow -5" },
  { on = [
    "I",
  ], exec = "arrow 5" },

  { on = [
    "n",
  ], exec = [
    "leave",
  ] },
  { on = [
    "o",
  ], exec = [
    "plugin --sync enter-or-open",
  ] },

  { on = [
    "N",
  ], exec = "back" },
  { on = [
    "O",
  ], exec = "forward" },

  { on = [
    "<C-i>",
  ], exec = "peek -5" },
  { on = [
    "<C-e>",
  ], exec = "peek 5" },

  # Operation
  { on = [
    "l",
  ], exec = "link" },
  { on = [
    "L",
  ], exec = "link --relative" },

  # Find
  { on = [
    "k",
  ], exec = "find_arrow" },
  { on = [
    "K",
  ], exec = "find_arrow --previous" },

  # Tab
  { on = [
    "[",
  ], exec = "tab_switch -1 --relative" },
  { on = [
    "]",
  ], exec = "tab_switch 1 --relative" },
]


[tasks]

prepend_keymap = [
  { on = [
    "i",
  ], exec = "arrow -1" },
  { on = [
    "e",
  ], exec = "arrow 1" },
]

[select]

prepend_keymap = [
  { on = [
    "i",
  ], exec = "arrow -1" },
  { on = [
    "e",
  ], exec = "arrow 1" },

  { on = [
    "I",
  ], exec = "arrow -5" },
  { on = [
    "E",
  ], exec = "arrow 5" },
]

[input]

prepend_keymap = [
  { on = ["h"], exec = "insert" },

  # Navigation
  { on = ["n"], exec = "move -1" },
  { on = ["o"], exec = "move 1" },

  { on = ["N"], exec = "move -999" },
  { on = ["O"], exec = "move 999" },

  { on = ["j"], exec = "forward --end-of-word" },
]

[help]

prepend_keymap = [
  # Navigation
  { on = ["i"], exec = "arrow -1" },
  { on = ["e"], exec = "arrow 1" },

  { on = ["I"], exec = "arrow -5" },
  { on = ["E"], exec = "arrow 5" },
]

[completion]

prepend_keymap = [
  { on = [
    "<C-i>",
  ], exec = "arrow -1" },
  { on = [
    "<C-e>",
  ], exec = "arrow 1" },
]
