[manager]

keymap = [
  { on = ["<Esc>"], exec = "escape" },
  { on = ["q"], exec = "quit" },
  { on = ["<C-q>"], exec = "close" },
  { on = ["<C-z>"], exec = '''shell "$SHELL" --block --confirm''' },

  # Navigation
  { on = ["i"], exec = "arrow -1" },
  { on = ["e"], exec = "arrow 1" },

  { on = ["E"], exec = "arrow -5" },
  { on = ["I"], exec = "arrow 5" },

  { on = ["n"], exec = ["leave", "escape --visual --select"] },
  { on = ["o"], exec = ["enter", "escape --visual --select"] },

  { on = ["N"], exec = "back" },
  { on = ["O"], exec = "forward" },

  { on = ["<C-i>"], exec = "peek -5" },
  { on = ["<C-e>"], exec = "peek 5" },

  { on = ["g", "g"], exec = "arrow -99999999" },
  { on = ["G"], exec = "arrow 99999999" },

  # Selection
  { on = ["<Space>"], exec = ["select --state=none", "arrow 1"] },
  { on = ["v"], exec = "visual_mode" },
  { on = ["V"], exec = "visual_mode --unset" },
  { on = ["<C-a>"], exec = "select_all --state=true" },
  { on = ["<C-r>"], exec = "select_all --state=none" },

  # Operation
  { on = ["<Enter>"], exec = "open" },
  { on = ["<C-Enter>"], exec = "open --interactive" },
  { on = ["y"], exec = ["yank", "escape --visual --select"] },
  { on = ["x"], exec = ["yank --cut", "escape --visual --select"] },
  { on = ["p"], exec = "paste" },
  { on = ["P"], exec = "paste --force" },
  { on = ["l"], exec = "link" },
  { on = ["L"], exec = "link --relative" },
  { on = ["d"], exec = ["remove", "escape --visual --select"] },
  { on = ["D"], exec = ["remove --permanently", "escape --visual --select"] },
  { on = ["a"], exec = "create" },
  { on = ["r"], exec = "rename" },
  { on = [";"], exec = "shell" },
  { on = [":"], exec = "shell --block" },
  { on = ["h"], exec = "hidden toggle" },
  { on = ["s"], exec = "search fd" },
  { on = ["S"], exec = "search rg" },
  { on = ["<C-s>"], exec = "search none" },
  { on = ["z"], exec = "jump zoxide" },
  { on = ["Z"], exec = "jump fzf" },

  # Linemode
  { on = ["m", "s"], exec = "linemode size" },
  { on = ["m", "p"], exec = "linemode permissions" },
  { on = ["m", "m"], exec = "linemode mtime" },
  { on = ["m", "n"], exec = "linemode none" },

  # Copy
  { on = ["c", "c"], exec = "copy path" },
  { on = ["c", "d"], exec = "copy dirname" },
  { on = ["c", "f"], exec = "copy filename" },
  { on = ["c", "n"], exec = "copy name_without_ext" },

  # Find
  { on = ["/"], exec = "find --smart" },
  { on = ["?"], exec = "find --previous --smart" },
  { on = ["-"], exec = "find_arrow" },
  { on = ["="], exec = "find_arrow --previous" },

  # Sorting
  { on = [",", "a"], exec = "sort alphabetical --dir_first" },
  { on = [",", "A"], exec = "sort alphabetical --reverse --dir_first" },
  { on = [",", "n"], exec = "sort natural --dir_first" },
  { on = [",", "N"], exec = "sort natural --reverse --dir_first" },
  { on = [",", "c"], exec = "sort created --reverse --dir_first" },
  { on = [",", "C"], exec = "sort created --dir_first" },
  { on = [",", "m"], exec = "sort modified --reverse --dir_first" },
  { on = [",", "M"], exec = "sort modified --dir_first" },
  { on = [",", "s"], exec = "sort size --reverse --dir_first" },
  { on = [",", "S"], exec = "sort size --dir_first" },

  # Tabs
  { on = ["<C-t>"], exec = "tab_create --current" },

  { on = ["<C-n>"], exec = "tab_switch -1 --relative" },
  { on = ["<C-o>"], exec = "tab_switch 1 --relative" },

  { on = ["1"], exec = "tab_switch 0" },
  { on = ["2"], exec = "tab_switch 1" },
  { on = ["3"], exec = "tab_switch 2" },
  { on = ["4"], exec = "tab_switch 3" },
  { on = ["5"], exec = "tab_switch 4" },
  { on = ["6"], exec = "tab_switch 5" },
  { on = ["7"], exec = "tab_switch 6" },
  { on = ["8"], exec = "tab_switch 7" },
  { on = ["9"], exec = "tab_switch 8" },

  { on = ["<"], exec = "tab_swap -1" },
  { on = [">"], exec = "tab_swap 1" },

  # Tasks
  { on = ["w"], exec = "tasks_show" },

  # Goto
  { on = ["g", "h"], exec = "cd ~" },
  { on = ["g", "c"], exec = "cd ~/.config" },
  { on = ["g", "d"], exec = "cd ~/Downloads" },
  { on = ["g", "t"], exec = "cd /tmp" },
  { on = ["g", "C"], exec = 'cd ~/.local/share/chezmoi' },
  { on = ["g", "<Space>"], exec = "cd --interactive" },

  # Help
  { on = ["~"], exec = "help" },
]

[tasks]

keymap = [
  { on = [
    "<C-q>",
  ], exec = "close" },
  { on = [
    "<Esc>",
  ], exec = "close" },
  { on = [
    "w",
  ], exec = "close" },

  { on = [
    "i",
  ], exec = "arrow -1" },
  { on = [
    "e",
  ], exec = "arrow 1" },

  { on = [
    "<Enter>",
  ], exec = "inspect" },
  { on = [
    "x",
  ], exec = "cancel" },

  { on = [
    "~",
  ], exec = "help" },
]

[select]

keymap = [
  { on = [
    "<C-q>",
  ], exec = "close" },
  { on = [
    "<Esc>",
  ], exec = "close" },
  { on = [
    "<Enter>",
  ], exec = "close --submit" },

  { on = [
    "i",
  ], exec = "arrow -1" },
  { on = [
    "e",
  ], exec = "arrow 1" },

  { on = [
    "I",
  ], exec = "arrow -5" },
  { on = [
    "E",
  ], exec = "arrow 5" },

  { on = [
    "~",
  ], exec = "help" },
]

[input]

keymap = [
  { on = ["<C-q>"], exec = "close" },
  { on = ["<Enter>"], exec = "close --submit" },
  { on = ["<Esc>"], exec = "escape" },
  { on = ["<Backspace>"], exec = "backspace" },

  # Mode
  { on = ["h"], exec = "insert" },
  { on = ["a"], exec = "insert --append" },
  { on = ["v"], exec = "visual" },
  { on = ["V"], exec = ["move -999", "visual", "move 999"] },

  # Navigation
  { on = ["n"], exec = "move -1" },
  { on = ["o"], exec = "move 1" },

  { on = ["N"], exec = "move -999" },
  { on = ["O"], exec = "move 999" },
  { on = ["<C-n>"], exec = ["move -999", "insert"] },
  { on = ["<C-i>"], exec = ["move 999", "insert --append"] },

  { on = ["b"], exec = "backward" },
  { on = ["w"], exec = "forward" },
  { on = ["j"], exec = "forward --end-of-word" },

  # Deletion
  { on = ["d"], exec = "delete --cut" },
  { on = ["D"], exec = ["delete --cut", "move 999"] },
  { on = ["c"], exec = "delete --cut --insert" },
  { on = ["C"], exec = ["delete --cut --insert", "move 999"] },
  { on = ["x"], exec = ["delete", "move 1 --in-operating"] },

  # Copy/Paste
  { on = ["y"], exec = ["yank"] },
  { on = ["p"], exec = ["paste"] },
  { on = ["P"], exec = ["paste --before"] },

  # Undo/Redo
  { on = ["u"], exec = ["undo"] },
  { on = ["U"], exec = ["redo"] },

  # Help
  { on = ["~"], exec = "help" },
]

[help]

keymap = [
  { on = ["<Esc>"], exec = "escape" },
  { on = ["q"], exec = "close" },
  { on = ["<C-q>"], exec = "close" },

  # Navigation
  { on = ["i"], exec = "arrow -1" },
  { on = ["e"], exec = "arrow 1" },

  { on = ["I"], exec = "arrow -5" },
  { on = ["E"], exec = "arrow 5" },

  # Filtering
  { on = ["/"], exec = "filter" },
]

[completion]

keymap = [
  { on = [
    "<C-q>",
  ], exec = "close" },
  { on = [
    "<Tab>",
  ], exec = "close --submit" },

  { on = [
    "<C-i>",
  ], exec = "arrow -1" },
  { on = [
    "<C-e>",
  ], exec = "arrow 1" },

  { on = [
    "~",
  ], exec = "help" },
]
