"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]

prepend_keymap = [
  { on = [
    "w",
  ], run = 'shell "$SHELL" --block --confirm', desc = "Open shell here" },
  { on = [
    "W",
  ], run = "tasks_show" },

  # Navigation
  { on = [
    "i",
  ], run = "arrow -1" },
  { on = [
    "e",
  ], run = "arrow 1" },

  { on = [
    "E",
  ], run = "arrow -5" },
  { on = [
    "I",
  ], run = "arrow 5" },

  { on = [
    "n",
  ], run = [
    "leave",
  ] },
  { on = [
    "o",
  ], run = [
    "plugin --sync enter-or-open",
  ] },

  { on = [
    "N",
  ], run = "back" },
  { on = [
    "O",
  ], run = "forward" },

  { on = [
    "<C-u>",
  ], run = "seek -5" },
  { on = [
    "<C-d>",
  ], run = "seek 5" },

  { on = [
    "h",
  ], run = "hidden toggle" },

  # Operation
  { on = [
    "l",
  ], run = "link" },
  { on = [
    "L",
  ], run = "link --relative" },

  # Find
  { on = [
    "k",
  ], run = "find_arrow" },
  { on = [
    "K",
  ], run = "find_arrow --previous" },

  # Tab
  { on = [
    "[",
  ], run = "tab_switch -1 --relative" },
  { on = [
    "]",
  ], run = "tab_switch 1 --relative" },
]


[tasks]

prepend_keymap = [
  { on = [
    "i",
  ], run = "arrow -1" },
  { on = [
    "e",
  ], run = "arrow 1" },
]

[select]

prepend_keymap = [
  { on = [
    "i",
  ], run = "arrow -1" },
  { on = [
    "e",
  ], run = "arrow 1" },

  { on = [
    "I",
  ], run = "arrow -5" },
  { on = [
    "E",
  ], run = "arrow 5" },
]

[input]

prepend_keymap = [
  { on = ["h"], run = "insert" },

  # Navigation
  { on = ["n"], run = "move -1" },
  { on = ["o"], run = "move 1" },

  { on = ["N"], run = "move -999" },
  { on = ["O"], run = "move 999" },

  { on = ["j"], run = "forward --end-of-word" },
]

[help]

prepend_keymap = [
  # Navigation
  { on = ["i"], run = "arrow -1" },
  { on = ["e"], run = "arrow 1" },

  { on = ["I"], run = "arrow -5" },
  { on = ["E"], run = "arrow 5" },
]

[completion]

prepend_keymap = [
  { on = [
    "<C-u>",
  ], run = "arrow -1" },
  { on = [
    "<C-d>",
  ], run = "arrow 1" },
]
