[files]
extend-exclude = ["themes/*", "**.age"]
ignore-dot = true
ignore-files = true

[type.age]
extend-glob = ["*.age"]
check-file = false

[default]
binary = false

[default.extend-words]
ags = "ags"
crypted = "crypted"
nore = "nore"
