[[bookmark]]
key = "d"
path = "~/Downloads"

[[bookmark]]
key = "j"
path = "/home/johnson/.dotfiles/joshuto/.config/joshuto"

[[bookmark]]
key = "r"
path = "/"

[[bookmark]]
key = "c"
path = "~/.config"

[[bookmark]]
key = "D"
path = "~/Documents"

[[bookmark]]
key = "v"
path = "/home/johnson/.dotfiles/nvim/.config/nvim"

[[bookmark]]
key = "R"
path = "~/Repos"

[[bookmark]]
key = "e"
path = "/etc"

[[bookmark]]
key = "p"
path = "/home/johnson/projects"

[[bookmark]]
key = "h"
path = "~/"
