# Use custom format:
format='''
$directory$git_branch$git_status$c$cmake$lua$python$rust$golang$java$nodejs$conda$docker_context$container$package
$character
'''

# Prompt symbols
[character]
success_symbol = "[](#9ece6a bold)"
error_symbol = "[](#db4b4b)"
vicmd_symbol = "[](#9ece6a)"
vimcmd_replace_one_symbol = "[](#d19a66)"
vimcmd_replace_symbol = "[](#e0af6e)"
vimcmd_visual_symbol = "[](#c678dd)"

[os]
format = "[]($style)[$symbol](bg:#292E42 fg:#7aa2f7)"
# style = "bg:#292E42 fg:#7aa2f7"
style = "bg:#1a1b26 fg:#292E42"

[os.symbols]
Windows = " "
Macos = " "
FreeBSD = " "
Android = "󰀲 "
Alpine = " "
Amazon = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
Garuda = " "
Gentoo = " "
HardenedBSD = " "
Illumos = " "
Linux = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
OpenCloudOS = " "
openEuler = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = " "
SUSE = " "
Ubuntu = " "
Unknown = " "

[directory]
read_only = "  "
read_only_style = "bg:#292E42 fg:#db4b4b"
format = "[]($style)[ ](bg:#292E42 fg:#7aa2f7)[[$path](bg:#292E42 fg:#a9b1d6)](bg:#292E42 fg:#c0caf5)[$read_only]($read_only_style)[ ]($style)"
style = "bg:#1a1b26 fg:#292E42"

[git_branch]
symbol = " "
format = "[]($style)[[$symbol](bg:#292E42 fg:#9ece6a)[$branch](bg:#292E42 fg:#a9b1d6)](bg:#292E42 fg:#c0caf5)"
style = "bg:#1a1b26 fg:#292E42"

[git_status]
format = "[ $all_status$ahead_behind]($style)[ ](bg:#1a1b26 fg:#292E42)"
style = "bg:#292E42 fg:#db4b4b"
conflicted = " "
up_to_date = " "
untracked = "󰷌 "
modified = " "
renamed = " "
deleted = " "
staged = " "
ahead = "󰜷"
diverged = "󰹺"
behind = "󰜮"
stashed = "󰋻 "

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[aws]
symbol = "  "

[buf]
symbol = ""

[c]
symbol = " "
format = "[]($style)[$symbol($version(-$name))](bg:#292e42 fg:#4abaaf)[ ]($style)"
style = "bg:#1a1b26 fg:#292E42"

[cmake]
symbol = "󰔶 "
format = "[]($style)[$symbol($version)](bg:#292e42 fg:#7aa2f7)[ ]($style)"
style = "bg:#1a1b26 fg:#292E42"

[conda]
symbol = " "
format = "[]($style)[$symbol$environment](bg:#292e42 fg:#98c379)[ ]($style)"
style = "bg:#1a1b26 fg:#292E42"

[container]
format = "[]($style)[$symbol$name](bg:#292e42 fg:#9a7ecc)[ ]($style)"
style = "bg:#1a1b26 fg:#292E42"

[dart]
symbol = " "

[docker_context]
symbol = " "
format = "[]($style)[$symbol$context](bg:#292e42 fg:#61afef)[ ]($style)"
style = "bg:#1a1b26 fg:#292E42"

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "
format = "[]($style)[$symbol$version](bg:#292e42 fg:#56b6c2)[ ]($style)"
style = "bg:#1a1b26 fg:#292E42"

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "
format = "[]($style)[$symbol$version](bg:#292e42 fg:#abb2bf)[ ]($style)"
style = "bg:#1a1b26 fg:#292E42"

[julia]
symbol = " "

[lua]
symbol = " "
format = "[]($style)[$symbol$version](bg:#292e42 fg:#61afef)[ ]($style)"
style = "bg:#1a1b26 fg:#292E42"

[memory_usage]
symbol = " "

[meson]
symbol = "喝"

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "
format = "[]($style)[$symbol$version](bg:#292e42 fg:#98c379)[ ]($style)"
style = "bg:#1a1b26 fg:#292E42"

[package]
symbol = " "
format = "[]($style)[$symbol$version](bg:#292e42 fg:#9a7ecc)[ ]($style)"
style = "bg:#1a1b26 fg:#292E42"

[python]
symbol = " "
format = "[]($style)[${symbol}${pyenv_prefix}${version}$virtualenv](bg:#292e42 fg:#e0af68)[ ]($style)"
style = "bg:#1a1b26 fg:#292E42"

[rlang]
symbol = "ﳒ "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "
format = "[]($style)[$symbol$version](bg:#292e42 fg:#e06c75)[ ]($style)"
style = "bg:#1a1b26 fg:#292E42"

[scala]
symbol = " "

[spack]
symbol = "🅢 "

