---
- name: icons
  become: true
  copy:
    dest: /usr/share/icons/Bibata-Modern-TokyoNight/
    src: "{{ role_files }}/Bibata-Modern-TokyoNight/"
    owner: root
    group: root
    mode: 0755

- name: icons index
  become: true
  file:
    dest: /usr/share/icons/default
    src: "{{ role_files }}/default"
    state: link
    force: true
