---
- name: Git Clone Bibata-Modern-TokyoNight
  git:
    repo: "https://github.com/huwqchn/Bibata-Modern-TokyoNight.git"
    dest: "~/.icons/Bibata-Modern-TokyoNight"
    update: false

- name: Sync Bibata-Modern-TokyoNight
  become: true
  synchronize:
    dest: "/usr/share/icons/Bibata-Modern-TokyoNight/"
    src: "~/.icons/Bibata-Modern-TokyoNight/"
    rsync_opts:
      - "--exclude=.git"

- name: remove icon default
  become: true
  file:
    state: absent
    path: /usr/share/icons/default/

- name: icons index
  become: true
  file:
    dest: /usr/share/icons/default
    src: "{{ role_files }}/default"
    state: link
    force: true

- name: remove local icon default
  file:
    state: absent
    path: ~/.icons/default/

- name: local icons index
  file:
    dest: ~/.icons/default
    src: "{{ role_files }}/default"
    state: link
    force: true
