---
- name: ensure docker is installed
  package:
    name: docker
    state: present

- name: ensure docker is running
  service:
    name: docker
    state: started

- name: pull and run clash container
  docker_container:
    name: clash
    image: dreamacro/clash
    state: started
    network_mode: host
    volumes:
      - "$HOME/.config/clash:/root/.config/clash"
