---
- name: install fonts
  become: true
  package:
    name:
      - ttf-victor-mono-nerd
      - ttf-dejavu-nerd
      - ttf-firacode-nerd
      - ttf-fira-code
      - ttf-font-awesome
      - ttf-hack-nerd
      - ttf-iosevka-nerd
      - ttf-meslo-nerd
      - ttf-terminus-nerd
      - ttf-ubuntu-mono-nerd
      - ttf-terminus-nerd
      - ttf-droid
      - ttf-jetbrains-mono-nerd
      - ttf-liberation
      - ttf-roboto
      - ttf-sourcecodepro-nerd
      - ttf-fantasque-sans-mono
      - adobe-source-han-serif-cn-fonts
      - otf-font-awesome
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
      - noto-fonts-extra

- name: install fonts from aur
  kewlfft.aur.aur:
    use: paru
    state: present
    name:
      - ttf-maple
      - ttf-material-design-icons-desktop-git
      - ttf-unifont
      - ttf-all-the-icons
      - ttf-poppins
      - ttf-weather-icons
