- name: Download Nerd Fonts
  include_tasks: download.yml
  loop:
    - FiraCode
    - DejaVuSansMono
    - JetBrainsMono
    - FantasqueSansMono
    - VictorMono
    - SourceCodePro
    - Hack

- name: install fonts
  become: true
  package:
    name:
      - google-roboto-fonts
      - ttf-maple
      - ttf-fira-code
      - ttf-fantasque-sans-mono
